id: I89F48B24
ocr_import_info:
  timestamp: '2023-10-06T15:22:15.156078+00:00'
  batch_id: batch-3d0d
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-07 06:24:39.113827+00:00
last_modified: 2023-10-07 06:24:39.113832+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W23760
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23760
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྫོགས་པ་ཆེན་པོ་ངལ་གསོ་སྐོར་གསུམ་དང་རང་གྲོལ་སྐོར་གསུམ་བཅས་པོད་གསུམ།
  languages:
  - bo
  author: ཀློང་ཆེན་རབ་འབྱམས་པ་དྲི་མེད་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.9792830218244908
  ocr_word_median_confidence_index: 0.9998959
bases:
  I2629:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2629
      total_pages: 770
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2629.txt
    statistics:
      ocr_word_median_confidence_index: 0.99991788
      ocr_word_mean_confidence_index: 0.9796762304647214
  I2630:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2630
      total_pages: 432
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2630.txt
    statistics:
      ocr_word_median_confidence_index: 0.99993676
      ocr_word_mean_confidence_index: 0.9801188731121872
  I2628:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2628
      total_pages: 734
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2628.txt
    statistics:
      ocr_word_median_confidence_index: 0.99982953
      ocr_word_mean_confidence_index: 0.9783808058447735
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
